[package]
name = "gateway"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0 OR MIT"

[dependencies]
anyhow = "1.0"
axum = { version = "0.7", features = ["http2"] }
tokio = { version = "1.38", features = ["rt-multi-thread", "macros", "fs"] }
tower = "0.5"
tower-http = { version = "0.5", features = ["compression-full", "trace"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
clap = { version = "4.5", features = ["derive"] }
index = { path = "../index" }
naming = { path = "../naming" }
mime_guess = "2.0"
tokio-util = { version = "0.7", features = ["io"] }
serde = { version = "1", features = ["derive"] }
toml = "0.8"
bytes = "1.7"
