name: api-stability
on:
  pull_request:
    paths:
      - "src/**"
      - "Cargo.toml"
jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: public api (placeholder)
        run: echo "wire cargo-public-api / semver-checks here"
