# deny.toml — cargo-deny >= 0.18

[graph]
all-features = true
exclude-dev = false

[advisories]
unmaintained = "workspace"
yanked = "deny"
ignore = []

[bans]
multiple-versions = "deny"
wildcards = "deny"
allow-wildcard-paths = true

# ---- Duplicate-version handling ---------------------------------------------
# Prefer unifying in Cargo.toml first; these skips are scoped to legacy stacks.

# Known trees that drag legacy stacks (notify->mio0.8, sled->parking_lot0.11)
skip-tree = [
  { name = "notify" },
  { name = "sled" },

  # Windows split crates — keep only the newest line counting toward duplicates
  { name = "windows-sys",     version = "< 0.60.2" },
  { name = "windows-targets", version = "< 0.53.3" },
  { name = "windows_i686_gnu",        version = "< 0.53.0" },
  { name = "windows_i686_gnullvm",    version = "< 0.53.0" },
  { name = "windows_i686_msvc",       version = "< 0.53.0" },
  { name = "windows_x86_64_gnu",      version = "< 0.53.0" },
  { name = "windows_x86_64_gnullvm",  version = "< 0.53.0" },
  { name = "windows_x86_64_msvc",     version = "< 0.53.0" },
  { name = "windows_aarch64_gnullvm", version = "< 0.53.0" },
  { name = "windows_aarch64_msvc",    version = "< 0.53.0" },
]

# Keep newest lines; skip only the *older* ones we still encounter.
skip = [
  # Compression: tldctl pulls brotli 3.x; async-compression uses 8.x
  { name = "brotli",              version = "< 8.0.0" },
  { name = "brotli-decompressor", version = "< 5.0.0" },

  # macOS security stack: native-tls vs rustls-native-certs pull different versions
  { name = "core-foundation",     version = "< 0.10.0" },
  { name = "security-framework",  version = "< 3.0.0" },

  # Mixed majors: prometheus 0.14 pulls thiserror 2.x; some deps still require 1.x
  { name = "thiserror",           version = "< 2.0.0" },
  { name = "thiserror-impl",      version = "< 2.0.0" },

  # Unavoidable splits:
  # - ring 0.17 currently pulls getrandom 0.2
  { name = "getrandom",  version = "< 0.3.0" },
  { name = "rand_core",  version = "< 0.9.0" },
]

# ---- Drift clamps (deny any version outside workspace pins) ------------------

# Tokio pinned to 1.47.1
[[bans.deny]]
name = "tokio"
version = "< 1.47.1"
reason = "Pin tokio to workspace version"
[[bans.deny]]
name = "tokio"
version = "> 1.47.1"
reason = "Pin tokio to workspace version"

# Axum pinned to 0.7.9
[[bans.deny]]
name = "axum"
version = "< 0.7.9"
reason = "Pin axum to workspace version"
[[bans.deny]]
name = "axum"
version = "> 0.7.9"
reason = "Pin axum to workspace version"

# Reqwest allowed only on 0.12.x
[[bans.deny]]
name = "reqwest"
version = "< 0.12.0"
reason = "Require reqwest 0.12.x"
[[bans.deny]]
name = "reqwest"
version = ">= 0.13.0"
reason = "Require reqwest 0.12.x"

# Prometheus allowed only on 0.14.x
[[bans.deny]]
name = "prometheus"
version = "< 0.14.0"
reason = "Require prometheus 0.14.x"
[[bans.deny]]
name = "prometheus"
version = ">= 0.15.0"
reason = "Require prometheus 0.14.x"

# Tokio-rustls pinned to 0.26.2
[[bans.deny]]
name = "tokio-rustls"
version = "< 0.26.2"
reason = "Pin tokio-rustls to workspace version"
[[bans.deny]]
name = "tokio-rustls"
version = "> 0.26.2"
reason = "Pin tokio-rustls to workspace version"

# Tower-HTTP pinned to 0.6.6
[[bans.deny]]
name = "tower-http"
version = "< 0.6.6"
reason = "Pin tower-http to workspace version"
[[bans.deny]]
name = "tower-http"
version = "> 0.6.6"
reason = "Pin tower-http to workspace version"

# Rand family unified on 0.9.x
[[bans.deny]]
name = "rand"
version = "< 0.9.0"
reason = "Unify rand to 0.9.x"
[[bans.deny]]
name = "rand"
version = ">= 0.10.0"
reason = "Unify rand to 0.9.x"
[[bans.deny]]
name = "rand_chacha"
version = "< 0.9.0"
reason = "Unify rand_chacha to 0.9.x"
[[bans.deny]]
name = "rand_chacha"
version = ">= 0.10.0"
reason = "Unify rand_chacha to 0.9.x"

# Regex unified on 1.11.x
[[bans.deny]]
name = "regex"
version = "< 1.11.0"
reason = "Unify regex to 1.11.x"
[[bans.deny]]
name = "regex"
version = ">= 1.12.0"
reason = "Unify regex to 1.11.x"

# ---- Workspace dependency guard (soften to warnings for now) -----------------
[bans.workspace-dependencies]
duplicates = "warn"
include-path-dependencies = true
unused = "warn"

[licenses]
unused-allowed-license = "allow"
confidence-threshold = 0.93

allow = [
  "Apache-2.0",
  "MIT",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "ISC",
  "Zlib",
  "OpenSSL",
  "CC0-1.0",
  "CDLA-Permissive-2.0",
  "Unicode-3.0",
  "Unicode-DFS-2016"
]
exceptions = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-git = []
