name: Render Mermaid
on:
  workflow_dispatch: {}
jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Render arch/sequence/state diagrams placeholder."
