[package]
name = "svc-wallet2"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[package.metadata.docs]
msrv = "1.80.0"

[features]
default = ["tls"]
tls = []
arti = []         # optional Tor transport feature
legacy_pay = []   # guarded legacy behavior (off by default)

[dependencies]
anyhow = "1"
thiserror = "2"
tokio = { version = "1", features = ["rt-multi-thread","macros","time","io-util"] }
axum = { version = "0.7", features = ["tokio","http1","http2","json"] }
tower = "0.5"
tower-http = { version = "0.6", features = ["trace","limit","timeout","compression-gzip"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1"
prometheus = "0.14"
tokio-rustls = "0.26"
http = "1"
hyper = { version = "1", features = ["http1","server"] }
blake3 = "1"

[dev-dependencies]
criterion = "0.5"
tokio = { version = "1", features = ["rt-multi-thread","macros","time","io-util","test-util"] }
