schema_version = 2
tld = "text"
address = "b3:0900f0d8c6d7f6f5f665bcf9961f965477a4020b14846fbf6b07081e6dcb9bef.text"
hash_algo = "b3"
hash_hex = "0900f0d8c6d7f6f5f665bcf9961f965477a4020b14846fbf6b07081e6dcb9bef"
bytes = 9
created_utc = "2025-08-24T23:49:36.67845Z"
mime = "text/plain; charset=utf-8"
stored_filename = "payload.bin"
original_filename = "rel.txt"
license = "CC-BY-4.0"

[[encodings]]
coding = "zstd"
level = 15
bytes = 18
filename = "payload.bin.zst"
hash_hex = "ae384a2b2056114c8509416acf27499ec9d33af9b6e2edcec06e34954ec9cbbc"

[[encodings]]
coding = "br"
level = 9
bytes = 13
filename = "payload.bin.br"
hash_hex = "8c28ffd360fd28498a0cbd2186588f2798cdb04f73fe3bdd53f098ce649eab4d"

[relations]
parent = "b3:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.text"
thread = "b3:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb.text"

[ext.image]
height = "600"
width = "800"

[ext.seo]
title = "Hello World"
