[package]
name = "tldctl"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
anyhow = "1"
blake3 = "1.5"
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
time = { version = "0.3", features = ["formatting"] }
toml = "0.8"
zstd = "0.13"
brotli = "3"

index = { path = "../index" }
naming = { path = "../naming" }

[[bin]]
name = "tldctl"
path = "src/main.rs"
