[package]
name = "tldctl"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
# Workspace-pinned deps
anyhow = { workspace = true }
blake3 = { workspace = true }
clap = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }
zstd = { workspace = true }
index = { workspace = true }
naming = { workspace = true }

# Local / external deps not pinned at workspace
time = { version = "0.3", features = ["formatting"] }
# Align brotli with the version pulled in by async-compression to avoid dupes.
brotli = "8"
infer = "0.15"
ryker = { path = "../ryker" }

# Hakari feature unifier
workspace-hack = { version = "0.1", path = "../../workspace-hack" }

[[bin]]
name = "tldctl"
path = "src/main.rs"
