[package]
name = "tldctl"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0 OR MIT"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
naming = { path = "../naming" }
index = { path = "../index" }
chrono = { version = "0.4", features = ["clock"] }