[package]
name = "tldctl"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
anyhow = { workspace = true }
blake3 = { workspace = true }
clap = { workspace = true }
serde = { workspace = true }
time = { version = "0.3", features = ["formatting"] }
toml = "0.8"
zstd = "0.13"
brotli = "3"
infer = "0.15" 
ryker = { path = "../ryker" }
index = { workspace = true }
naming = { workspace = true }
workspace-hack = { version = "0.1", path = "../../workspace-hack" }

[[bin]]
name = "tldctl"
path = "src/main.rs"
