[package]
publish = false
license = "MIT OR Apache-2.0"


name = "overlay"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
blake3 = { workspace = true }
sled = { workspace = true }
hex = { workspace = true }
tracing = "0.1"
serde = { workspace = true }
lru = "0.12"                             # NEW: in-memory cache
tokio = { workspace = true, features = ["full"] }
thiserror = { workspace = true }
transport = { workspace = true }
workspace-hack = { workspace = true }

