[package]
name = "svc-interop2-fuzz"
version = "0.1.0"
publish = false

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[workspace]
members = []

[[bin]]
name = "dto_parse"
path = "fuzz_targets/dto_parse.rs"
test = false
doc = false

[[bin]]
name = "webhook_sig"
path = "fuzz_targets/webhook_sig.rs"
test = false
doc = false

[[bin]]
name = "decompression"
path = "fuzz_targets/decompression.rs"
test = false
doc = false
