[package]
publish = false
license = "MIT OR Apache-2.0"
name = "ronctl"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
hex = { workspace = true }
rmp-serde = { workspace = true }
ron-bus = { workspace = true }
serde = { workspace = true }

# unify RNG deps with workspace pins
rand        = { workspace = true, features = ["std"] }
rand_chacha = { workspace = true, features = ["std"] }

workspace-hack = { version = "0.1", path = "../../workspace-hack" }
