[package]
publish = false
license = "MIT OR Apache-2.0"


name = "ronctl"
version = "0.1.0"
edition = "2021"

[dependencies]
ron-bus = { path = "../../crates/ron-bus" }
rand = { version = "0.9", features = ["std"] }
rmp-serde = "1.3"
serde = { version = "1.0", features = ["derive"] }
clap = { version = "4.5", features = ["derive"] }
hex = "0.4"
anyhow = "1.0"
rand_chacha = { version = "0.9", features = ["std"] }
workspace-hack = { version = "0.1", path = "../../workspace-hack" }
