[package]
publish = false
license = "MIT OR Apache-2.0"


name = "ronctl"
version = "0.1.0"
edition = "2021"

[dependencies]
ron-bus = { workspace = true }
rand = { version = "0.9", features = ["std"] }
rmp-serde = { workspace = true }
serde = { workspace = true }
clap = { workspace = true }
hex = { workspace = true }
anyhow = { workspace = true }
rand_chacha = { version = "0.9", features = ["std"] }
workspace-hack = { version = "0.1", path = "../../workspace-hack" }
