# cargo-deny baseline (licenses, advisories, bans)
[advisories]
vulnerability = "deny"
yanked = "deny"

[licenses]
confidence-threshold = 0.8
allow = [
  "MIT", "Apache-2.0", "Unicode-DFS-2016", "BSD-3-Clause",
  "ISC", "CC0-1.0", "OpenSSL"
]
