schema_version = 2
tld = "text"
address = "b3:0b8b60248fad7ac6dfac221b7e01a8b91c772421a15b387dd1fb2d6a94aee438.text"
hash_algo = "b3"
hash_hex = "0b8b60248fad7ac6dfac221b7e01a8b91c772421a15b387dd1fb2d6a94aee438"
bytes = 3
created_utc = "2025-08-24T23:47:04.205626Z"
mime = "text/plain; charset=utf-8"
stored_filename = "payload.bin"
original_filename = "rel.txt"
license = "CC-BY-4.0"

[[encodings]]
coding = "zstd"
level = 15
bytes = 12
filename = "payload.bin.zst"
hash_hex = "599d02bd02d52fda0f15ce23f892369509774883687ed2a807318615f5ffceab"

[[encodings]]
coding = "br"
level = 9
bytes = 7
filename = "payload.bin.br"
hash_hex = "43d36908e24a102bf71c7fa619f3d0441d36bd67d7de515d0b9efebf2699c31f"

[relations]
parent = "b3:1111...aaaa.text"
thread = "b3:2222...bbbb.text"

[ext.image]
height = "600"
width = "800"

[ext.seo]
title = "Hello"
