# Example config for RustyOnions
dev_inbox_addr = "127.0.0.1:2888"
chunk_size = 65536
connect_timeout_ms = 5000
# Optional persistent HS private key file (used by `ronode serve --transport tor`)
# hs_key_file = ".data/hs_ed25519_key"
data_dir = "/var/folders/nw/36byqj_s4_v5bz8zd_w52_680000gn/T/tor_test.bZT8Eenpnq/data"
socks5_addr = "127.0.0.1:19050"
tor_ctrl_addr = "127.0.0.1:19051"
overlay_addr = "127.0.0.1:1777"
