name: ci
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.80.0
      - run: cargo fmt --all --check
      - run: cargo clippy -p svc-wallet2 -- -D warnings
      - run: cargo test -p svc-wallet2
