[package]
publish = false
license = "MIT OR Apache-2.0"

name = "accounting"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
parking_lot = { workspace = true }
workspace-hack = { version = "0.1", path = "../../workspace-hack" }
