[package]
publish = false
license = "MIT OR Apache-2.0"


name = "node"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
color-eyre = "0.6"
# clap with derive + env var support
clap = { workspace = true }
overlay = { path = "../overlay" }
common = { path = "../common" }
# ✅ Tokio runtime + macros (needed for #[tokio::main]) + net + signal
tokio               = { workspace = true, features = ["rt-multi-thread","macros","net","signal"] }
tracing             = { workspace = true }
tracing-subscriber  = { workspace = true, features = ["env-filter"] }
transport = { workspace = true }
workspace-hack = { version = "0.1", path = "../../workspace-hack" }
