[package]
name = "node"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
common = { path = "../common" }
overlay = { path = "../overlay" }
transport = { path = "../transport" }
accounting = { path = "../accounting" }
