[package]
name = "gwsmoke"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
anyhow     = { workspace = true }
tokio      = { workspace = true, features = ["rt-multi-thread", "macros"] }
reqwest    = { workspace = true, features = ["json", "rustls-tls-native-roots"] }
serde      = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
# gwsmoke may spin a tiny test server; keep axum available but lean
axum       = { workspace = true, default-features = false, features = ["macros","http1"] }
workspace-hack = { version = "0.1", path = "../../workspace-hack" }
