[package]
name = "gwsmoke"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
regex = "1.10"
tokio = { version = "1.39", features = ["rt-multi-thread", "macros", "process", "fs", "time", "signal", "io-util"] }
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "gzip", "brotli", "deflate"] }
