[package]
name = "gwsmoke"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }

# Use workspace pin (1.11) to avoid regex dupes across workspace
regex = { workspace = true }

# Clamp tokio to workspace pin
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "process", "fs", "time", "signal", "io-util"] }

# Clamp reqwest to workspace pin; enable rustls + compression + json as used here
reqwest = { workspace = true, features = ["rustls-tls-native-roots", "gzip", "brotli", "deflate", "json"] }
workspace-hack = { version = "0.1", path = "../../workspace-hack" }
