[alias]
lint = "clippy -p ron-bus2 -- -D warnings"
test-all = "test -p ron-bus2 --all-features"
ci-check = "fmt --all && clippy -D warnings && test -p ron-bus2 && deny check"
bench-all = "bench -p ron-bus2"
