[package]
name = "arti_transport"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
accounting = { path = "../accounting" }
transport = { path = "../transport" }
# Synchronous SOCKS5 client for outbound via Tor
socks = "0.3"
hex = "0.4"