[package]
name = "arti_transport"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
socks = "0.3"
tracing = "0.1"

# local crates
transport = { path = "../transport" }
accounting = { path = "../accounting" }
