name: ron-transport2 Perf
on: { workflow_dispatch: {} }
jobs:
  perf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Run benches (placeholder)
        run: cargo bench -p ron-transport2 || true
      - name: Archive Criterion artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bench-artifacts
          path: target/criterion
