[package]
publish = false
license = "MIT OR Apache-2.0"


name = "ron-bus"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
rmp-serde = "1.3"
thiserror = "1.0"
workspace-hack = { version = "0.1", path = "../../workspace-hack" }
