// invariants & caps placeholder — (auto-generated by scaffold_svc_index2.sh; replace with real content later)
pub const OAP_MAX_FRAME_BYTES: usize = 1_048_576; // 1 MiB
pub const DECOMP_MAX_RATIO: u32 = 10;
pub const DEFAULT_DEADLINE_MS: u64 = 1200;
pub const DEFAULT_INFLIGHT: usize = 1024;
