[package]
name = "ron-policy-fuzz"
version = "0.1.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
serde_json = "1.0"
toml = "0.8"
ron-policy = { path = ".." }

[[bin]]
name = "fuzz_bundle_parse"
path = "fuzz_targets/fuzz_bundle_parse.rs"

[[bin]]
name = "fuzz_eval"
path = "fuzz_targets/fuzz_eval.rs"
