//! RO:WHAT — Focused Physical M1 tests for bounded Native Passport device-key generation.
//! RO:WHY — Proves canonical device keys come from an injected randomness boundary without adding persistence or root/network authority.
//! RO:INTERACTS — device_key_generation, device_identity, NativeSecretBytes, and Ed25519 public identity derivation.
//! RO:INVARIANTS — exactly 32 generated bytes; one randomness fill; failure is closed; generated secrets remain redacted and zeroizing.
//! RO:METRICS — none.
//! RO:CONFIG — native-passport feature only.
//! RO:SECURITY — deterministic sources exist only inside this test; production OS randomness is supplied by the native platform adapter.
//! RO:TEST — cargo test -p svc-passport --no-default-features --features native-passport --test physical_m1_native_device_key_generation.

#![cfg(feature = "native-passport")]

use std::{
    fs,
    path::PathBuf,
    sync::atomic::{AtomicUsize, Ordering},
};

use svc_passport::native::{
    derive_native_device_public_identity_v1, generate_native_device_signing_seed_v1_with_random,
    NativeDeviceKeyGenerationError, NativeDeviceKeyRandomSource, DEVICE_ID_V1_SIGNING_SEED_BYTES,
    PHYSICAL_M1_DEVICE_KEY_GENERATION_LABEL,
};

const SEQUENTIAL_TEST_SEED_PUBLIC_KEY_HEX: &str =
    "03a107bff3ce10be1d70dd18e74bc09967e4d6309ba50d5f1ddc8664125531b8";

struct SequentialRandom {
    calls: AtomicUsize,
}

impl SequentialRandom {
    fn new() -> Self {
        Self {
            calls: AtomicUsize::new(0),
        }
    }

    fn calls(&self) -> usize {
        self.calls.load(Ordering::SeqCst)
    }
}

impl NativeDeviceKeyRandomSource for SequentialRandom {
    fn fill(&self, output: &mut [u8]) -> Result<(), NativeDeviceKeyGenerationError> {
        self.calls.fetch_add(1, Ordering::SeqCst);

        for (index, byte) in output.iter_mut().enumerate() {
            *byte = u8::try_from(index).expect("32-byte test seed indices fit in u8");
        }

        Ok(())
    }
}

struct FailingRandom {
    calls: AtomicUsize,
}

impl FailingRandom {
    fn new() -> Self {
        Self {
            calls: AtomicUsize::new(0),
        }
    }

    fn calls(&self) -> usize {
        self.calls.load(Ordering::SeqCst)
    }
}

impl NativeDeviceKeyRandomSource for FailingRandom {
    fn fill(&self, output: &mut [u8]) -> Result<(), NativeDeviceKeyGenerationError> {
        self.calls.fetch_add(1, Ordering::SeqCst);

        if let Some(first) = output.first_mut() {
            *first = 0xaa;
        }

        Err(NativeDeviceKeyGenerationError::RandomnessUnavailable)
    }
}

#[test]
fn physical_m1_device_generation_contract_is_locked() {
    assert_eq!(
        PHYSICAL_M1_DEVICE_KEY_GENERATION_LABEL,
        "PHYSICAL_M1_NATIVE_DEVICE_KEY_GENERATION_V1",
    );

    assert_eq!(DEVICE_ID_V1_SIGNING_SEED_BYTES, 32,);
}

#[test]
fn physical_m1_injected_generation_produces_exactly_one_device_seed() {
    let random = SequentialRandom::new();

    let seed =
        generate_native_device_signing_seed_v1_with_random(&random).expect("generated device seed");

    assert_eq!(random.calls(), 1);
    assert_eq!(seed.len(), DEVICE_ID_V1_SIGNING_SEED_BYTES);

    let identity =
        derive_native_device_public_identity_v1(&seed).expect("derived public device identity");

    assert_eq!(
        identity.device_public_key.as_str(),
        SEQUENTIAL_TEST_SEED_PUBLIC_KEY_HEX,
    );
}

#[test]
fn physical_m1_generated_device_secret_debug_is_redacted() {
    let random = SequentialRandom::new();

    let seed =
        generate_native_device_signing_seed_v1_with_random(&random).expect("generated device seed");

    let debug = format!("{seed:?}");

    assert!(debug.contains("REDACTED"));

    assert!(!debug.contains("000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f",));
}

#[test]
fn physical_m1_randomness_failure_returns_no_device_secret() {
    let random = FailingRandom::new();

    let result = generate_native_device_signing_seed_v1_with_random(&random);

    assert_eq!(random.calls(), 1);

    assert_eq!(
        result.unwrap_err(),
        NativeDeviceKeyGenerationError::RandomnessUnavailable,
    );
}

#[test]
fn physical_m1_generation_source_has_no_persistence_or_authority() {
    let source_path =
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("src/native/device_key_generation.rs");

    let source = fs::read_to_string(source_path).expect("device-key generation source");

    for required in [
        "NativeDeviceKeyRandomSource",
        "Zeroizing",
        "NativeSecretBytes",
        "DEVICE_ID_V1_SIGNING_SEED_BYTES",
    ] {
        assert!(
            source.contains(required),
            "generation source missing {required}",
        );
    }

    for forbidden in [
        "getrandom::",
        "NativePlatformSealer",
        "NativeVaultStore",
        "seal_native_secret(",
        "unseal_native_secret(",
        "write_encrypted_vault_atomic(",
        "std::fs::",
        "tokio::fs",
        "#[tauri::command]",
        ".sign(",
        "issue_capability(",
        "wallet.spend(",
        "ledger.write(",
        "mint_roc(",
        "burn_roc(",
    ] {
        assert!(
            !source.contains(forbidden),
            "portable generation source gained forbidden runtime marker {forbidden}",
        );
    }
}
