name: perf-guardrails
on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"
jobs:
  perf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo bench -p ron-app-sdk2 || true