[package]
name = "ryker"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true }
naming = { workspace = true }
workspace-hack = { version = "0.1", path = "../../workspace-hack" }
