[package]
publish = false
license = "MIT OR Apache-2.0"


name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
blake3 = { workspace = true }
hex = { workspace = true }
thiserror = { workspace = true }
toml      = { workspace = true }
workspace-hack = { workspace = true }


