[package]
publish = false
license = "MIT OR Apache-2.0"


name = "svc-index"
version = "0.1.0"
edition = "2021"

[dependencies]
ron-bus = { path = "../ron-bus" }
index = { path = "../index" }
naming = { path = "../naming" }
serde = { version = "1.0", features = ["derive"] }
rmp-serde = "1.3"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter","json"] }
regex = "1"
workspace-hack = { version = "0.1", path = "../../workspace-hack" }
