[package]
publish = false
license = "MIT OR Apache-2.0"


name = "svc-index"
version = "0.1.0"
edition = "2021"

[dependencies]
ron-bus = { workspace = true }
index = { workspace = true }
naming = { workspace = true }
serde = { workspace = true }
rmp-serde = { workspace = true }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter","json"] }
regex = { workspace = true }
workspace-hack = { version = "0.1", path = "../../workspace-hack" }
