[package]
publish = false
license = "MIT OR Apache-2.0"

name = "svc-index"
version = "0.1.0"
edition = "2021"

[dependencies]
ron-bus = { workspace = true }
index = { workspace = true }
naming = { workspace = true }
serde = { workspace = true }
rmp-serde = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "json"] }
regex = { workspace = true }
workspace-hack = { version = "0.1", path = "../../workspace-hack" }
