[package]
name = "ron-naming"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "RON-CORE naming & addressing types (schema-only; no runtime lookups)."
repository = "https://github.com/RustyOnions/RustyOnions"
readme = "README.md"
categories = ["network-programming", "encoding", "data-structures"]
keywords = ["RON", "naming", "addressing", "BLAKE3", "IDNA"]

[features]
default = []
cli = ["dep:clap", "dep:anyhow", "dep:base64"]
verify = []

[dependencies]
# Core
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_cbor = "0.11"
thiserror = "1.0"
bytes = "1.6"
blake3 = "1.5"
semver = { version = "1.0", features = ["serde"] }

# Naming / normalization
idna = "0.5"
unicode-normalization = "0.1"
regex = "1.11"
once_cell = "1.19"

# CLI (feature-gated)
clap = { version = "4.5", features = ["derive"], optional = true }
anyhow = { version = "1.0", optional = true }
base64 = { version = "0.22", optional = true }

[dev-dependencies]
proptest = "1.5"
insta = { version = "1.39", features = ["yaml"] }
criterion = "0.5"
assert_cmd = "2.0"
predicates = "3.1"

[[bin]]
name = "tldctl"
path = "src/bin/tldctl.rs"
required-features = ["cli"]

[[bench]]
name = "normalize_bench"
harness = false

[[bench]]
name = "encode_bench"
harness = false
