[package]
publish = false
license = "MIT OR Apache-2.0"


name = "transport"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
tracing = "0.1"

# existing internal dep (keep if you're using it)
accounting = { path = "../accounting" }

# NEW: async traits
async-trait = "0.1"

# NEW: async runtime + net I/O used across TCP/Tor code
tokio = { version = "1", features = ["full"] }

# NEW: SOCKS5 client for Tor (SOCKS5h)
tokio-socks = "0.5"

# NEW: retry/backoff used by Tor control commands
retry = "2.0"

