#!/usr/bin/env bash
set -euo pipefail

# RO:WHAT — Aggregate per-crate docs/dump/ALL_DOCS.md files into root ALL_DOCS_COMBINED.MD.
# RO:WHY — Ops/DX; Concerns: GOV/DX. Keeps crate documentation dumps available in one project-wide file.
# RO:INTERACTS — crates/*/docs/dump/ALL_DOCS.md, COMPLETECRATELIST.MD, ALL_DOCS_COMBINED.MD.
# RO:INVARIANTS — canonical 33 crates first; extras discovered; missing docs visible as placeholders.
# RO:METRICS — none.
# RO:CONFIG — STRICT_CANON=1 excludes non-canon extras; FAIL_ON_MISSING=1 exits non-zero if listed docs missing.
# RO:SECURITY — reads local Markdown only; no secrets intentionally printed beyond file paths.
# RO:TEST — run: bash scripts/collect_all_docs.sh && grep '^## ' ALL_DOCS_COMBINED.MD.

# Collect docs/dump/ALL_DOCS.md from canonical crates, plus any extra crates
# with that file, into ALL_DOCS_COMBINED.MD at the repo root.

# Discover repo root: prefer git; fall back to script-relative.
if ROOT="$(git rev-parse --show-toplevel 2>/dev/null)"; then
  :
else
  SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
  ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
fi

OUT="$ROOT/ALL_DOCS_COMBINED.MD"
CRATES_DIR="$ROOT/crates"

# If STRICT_CANON=1, only the canonical 33 are included.
STRICT_CANON="${STRICT_CANON:-0}"

# If FAIL_ON_MISSING=1, missing ALL_DOCS.md files cause a non-zero exit.
FAIL_ON_MISSING="${FAIL_ON_MISSING:-0}"

timestamp() {
  date -u +"%Y-%m-%dT%H:%M:%SZ"
}

# Canonical RustyOnions crate order.
CANONICAL_CRATES=(
  "macronode"
  "micronode"
  "oap"
  "omnigate"
  "ron-accounting"
  "ron-app-sdk"
  "ron-audit"
  "ron-auth"
  "ron-bus"
  "ron-kernel"
  "ron-kms"
  "ron-ledger"
  "ron-metrics"
  "ron-naming"
  "ron-policy"
  "ron-proto"
  "ron-transport"
  "ryker"
  "svc-ads"
  "svc-dht"
  "svc-edge"
  "svc-gateway"
  "svc-index"
  "svc-interop"
  "svc-mailbox"
  "svc-mod"
  "svc-overlay"
  "svc-passport"
  "svc-registry"
  "svc-rewarder"
  "svc-sandbox"
  "svc-storage"
  "svc-wallet"
)

contains_crate() {
  local needle="$1"
  shift

  local item
  for item in "$@"; do
    if [[ "$item" == "$needle" ]]; then
      return 0
    fi
  done

  return 1
}

crate_dir_for() {
  local crate="$1"

  if [[ -d "$CRATES_DIR/$crate" ]]; then
    printf '%s\n' "$CRATES_DIR/$crate"
    return 0
  fi

  # Fallback for repos/checkouts where crates are laid out directly at root.
  if [[ -d "$ROOT/$crate" ]]; then
    printf '%s\n' "$ROOT/$crate"
    return 0
  fi

  printf '%s\n' "$CRATES_DIR/$crate"
}

all_docs_path_for() {
  local crate="$1"
  local crate_dir
  crate_dir="$(crate_dir_for "$crate")"
  printf '%s\n' "$crate_dir/docs/dump/ALL_DOCS.md"
}

discover_extra_crates_with_all_docs() {
  if [[ -d "$CRATES_DIR" ]]; then
    find "$CRATES_DIR" -mindepth 4 -maxdepth 4 -path "*/docs/dump/ALL_DOCS.md" -print \
      | while IFS= read -r docs_path; do
          crate_dir="$(dirname "$(dirname "$(dirname "$docs_path")")")"
          crate_name="$(basename "$crate_dir")"
          if ! contains_crate "$crate_name" "${CANONICAL_CRATES[@]}"; then
            printf '%s\n' "$crate_name"
          fi
        done
  fi

  # Fallback discovery for direct-root crate layout:
  # root/<crate>/docs/dump/ALL_DOCS.md
  find "$ROOT" -mindepth 4 -maxdepth 4 -path "*/docs/dump/ALL_DOCS.md" -print 2>/dev/null \
    | while IFS= read -r docs_path; do
        crate_dir="$(dirname "$(dirname "$(dirname "$docs_path")")")"
        crate_name="$(basename "$crate_dir")"

        # Skip crates already discovered under $ROOT/crates by name.
        if [[ "$crate_dir" == "$CRATES_DIR/"* ]]; then
          continue
        fi

        if ! contains_crate "$crate_name" "${CANONICAL_CRATES[@]}"; then
          printf '%s\n' "$crate_name"
        fi
      done \
    | sort -u
}

CRATES=("${CANONICAL_CRATES[@]}")

if [[ "$STRICT_CANON" != "1" ]]; then
  while IFS= read -r extra_crate; do
    [[ -z "$extra_crate" ]] && continue
    if ! contains_crate "$extra_crate" "${CRATES[@]}"; then
      CRATES+=("$extra_crate")
    fi
  done < <(discover_extra_crates_with_all_docs)
fi

missing_any=0
included_count=0
placeholder_count=0
extra_count=0

{
  echo "<!-- Generated by scripts/collect_all_docs.sh on $(timestamp) -->"
  echo "# ALL_DOCS_COMBINED — Crate Documentation Dump Aggregation"
  echo
  echo "_This file aggregates \`docs/dump/ALL_DOCS.md\` from RustyOnions crates._"
  echo
  echo "- Canonical crates are emitted first in stable project order."
  echo "- Extra crates with \`docs/dump/ALL_DOCS.md\` are appended alphabetically unless \`STRICT_CANON=1\`."
  echo "- Missing canonical docs receive placeholders so gaps are visible."
  echo
  echo "## Included crates"
  for c in "${CRATES[@]}"; do
    if contains_crate "$c" "${CANONICAL_CRATES[@]}"; then
      echo "- ${c}"
    else
      echo "- ${c} _(extra discovered crate)_"
    fi
  done
  echo
  echo "---"
  echo
} > "$OUT"

for c in "${CRATES[@]}"; do
  SRC="$(all_docs_path_for "$c")"

  if contains_crate "$c" "${CANONICAL_CRATES[@]}"; then
    echo ">> ${c}" >&2
  else
    echo ">> ${c} (extra discovered crate)" >&2
    extra_count=$((extra_count + 1))
  fi

  {
    echo
    echo "## ${c}"
    echo
    echo "<!-- BEGIN ${c} docs/dump/ALL_DOCS.md -->"
    echo

    if [[ -f "$SRC" ]]; then
      cat "$SRC"
      included_count=$((included_count + 1))
    else
      rel="${SRC#"$ROOT/"}"
      echo "_(No ALL_DOCS.md found at \`${rel}\` — skipped.)_"
      missing_any=1
      placeholder_count=$((placeholder_count + 1))
    fi

    echo
    echo "<!-- END ${c} docs/dump/ALL_DOCS.md -->"
    echo
    echo "---"
    echo
  } >> "$OUT"
done

{
  echo
  echo "## Generation Summary"
  echo
  echo "- Generated at: \`$(timestamp)\`"
  echo "- Canonical crate count: \`${#CANONICAL_CRATES[@]}\`"
  echo "- Total sections emitted: \`${#CRATES[@]}\`"
  echo "- ALL_DOCS.md files included: \`${included_count}\`"
  echo "- Missing placeholders inserted: \`${placeholder_count}\`"
  echo "- Extra discovered crates included: \`${extra_count}\`"
  echo "- STRICT_CANON: \`${STRICT_CANON}\`"
  echo
} >> "$OUT"

echo "Wrote: $OUT" >&2
echo "Included ALL_DOCS.md files: ${included_count}" >&2
echo "Missing placeholders: ${placeholder_count}" >&2
echo "Extra discovered crates: ${extra_count}" >&2

if [[ "$missing_any" -eq 1 ]]; then
  echo "Note: one or more listed crates had no docs/dump/ALL_DOCS.md; placeholders inserted." >&2
fi

if [[ "$missing_any" -eq 1 && "$FAIL_ON_MISSING" == "1" ]]; then
  echo "FAIL_ON_MISSING=1 and one or more ALL_DOCS.md files are missing." >&2
  exit 1
fi