#!/usr/bin/env bash
set -euo pipefail

# RO:WHAT — Aggregate per-crate NOTES.MD files into root ALLNOTES.MD.
# RO:WHY — Ops/DX; Concerns: GOV/DX. Keeps crate carry-over notes available in one project-wide file.
# RO:INTERACTS — crates/*/NOTES.MD, COMPLETECRATELIST.MD, ALLNOTES.MD.
# RO:INVARIANTS — canonical 33 crates first; extras discovered; no silent omission of existing NOTES.MD.
# RO:METRICS — none.
# RO:CONFIG — STRICT_CANON=1 excludes non-canon extras; FAIL_ON_MISSING=1 exits non-zero if listed notes missing.
# RO:SECURITY — reads local Markdown only; no secrets printed beyond file paths.
# RO:TEST — run: bash scripts/collect_notes.sh && grep '^## ' ALLNOTES.MD.

# Collect NOTES.MD from canonical crates, plus any extra crates with NOTES.MD,
# into ALLNOTES.MD at the repo root.

# Discover repo root (prefers git; falls back to script-relative).
if ROOT="$(git rev-parse --show-toplevel 2>/dev/null)"; then
  :
else
  SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
  ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
fi

OUT="$ROOT/ALLNOTES.MD"
CRATES_DIR="$ROOT/crates"

# If STRICT_CANON=1, only the canonical 33 are included.
STRICT_CANON="${STRICT_CANON:-0}"

# If FAIL_ON_MISSING=1, missing NOTES.MD files cause a non-zero exit.
FAIL_ON_MISSING="${FAIL_ON_MISSING:-0}"

timestamp() {
  date -u +"%Y-%m-%dT%H:%M:%SZ"
}

# Canonical RustyOnions crate order.
#
# This follows the fixed 33-crate canon used by the project blueprints:
# macronode, micronode, oap, omnigate, ron-accounting, ron-app-sdk,
# ron-audit, ron-auth, ron-bus, ron-kernel, ron-kms, ron-ledger,
# ron-metrics, ron-naming, ron-policy, ron-proto, ron-transport, ryker,
# svc-ads, svc-dht, svc-edge, svc-gateway, svc-index, svc-interop,
# svc-mailbox, svc-mod, svc-overlay, svc-passport, svc-registry,
# svc-rewarder, svc-sandbox, svc-storage, svc-wallet.
CANONICAL_CRATES=(
  "macronode"
  "micronode"
  "oap"
  "omnigate"
  "ron-accounting"
  "ron-app-sdk"
  "ron-audit"
  "ron-auth"
  "ron-bus"
  "ron-kernel"
  "ron-kms"
  "ron-ledger"
  "ron-metrics"
  "ron-naming"
  "ron-policy"
  "ron-proto"
  "ron-transport"
  "ryker"
  "svc-ads"
  "svc-dht"
  "svc-edge"
  "svc-gateway"
  "svc-index"
  "svc-interop"
  "svc-mailbox"
  "svc-mod"
  "svc-overlay"
  "svc-passport"
  "svc-registry"
  "svc-rewarder"
  "svc-sandbox"
  "svc-storage"
  "svc-wallet"
)

contains_crate() {
  local needle="$1"
  shift

  local item
  for item in "$@"; do
    if [[ "$item" == "$needle" ]]; then
      return 0
    fi
  done

  return 1
}

discover_extra_crates_with_notes() {
  if [[ ! -d "$CRATES_DIR" ]]; then
    return 0
  fi

  local dir
  find "$CRATES_DIR" -mindepth 2 -maxdepth 2 -name "NOTES.MD" -print \
    | while IFS= read -r notes_path; do
        dir="$(basename "$(dirname "$notes_path")")"
        if ! contains_crate "$dir" "${CANONICAL_CRATES[@]}"; then
          printf '%s\n' "$dir"
        fi
      done \
    | sort -u
}

CRATES=("${CANONICAL_CRATES[@]}")

if [[ "$STRICT_CANON" != "1" ]]; then
  while IFS= read -r extra_crate; do
    [[ -z "$extra_crate" ]] && continue
    CRATES+=("$extra_crate")
  done < <(discover_extra_crates_with_notes)
fi

missing_any=0
included_count=0
placeholder_count=0
extra_count=0

# Header.
{
  echo "<!-- Generated by scripts/collect_notes.sh on $(timestamp) -->"
  echo "# ALLNOTES — Crate Notes Aggregation"
  echo
  echo "_This file aggregates \`NOTES.MD\` from RustyOnions crates._"
  echo
  echo "- Canonical crates are emitted first in stable project order."
  echo "- Extra crates with \`NOTES.MD\` are appended alphabetically unless \`STRICT_CANON=1\`."
  echo "- Missing canonical notes receive placeholders so gaps are visible."
  echo
  echo "## Included crates"
  for c in "${CRATES[@]}"; do
    if contains_crate "$c" "${CANONICAL_CRATES[@]}"; then
      echo "- ${c}"
    else
      echo "- ${c} _(extra discovered crate)_"
    fi
  done
  echo
  echo "---"
  echo
} > "$OUT"

# Append each NOTES.MD with a section header and divider.
for c in "${CRATES[@]}"; do
  SRC="$CRATES_DIR/$c/NOTES.MD"

  if contains_crate "$c" "${CANONICAL_CRATES[@]}"; then
    echo ">> ${c}" >&2
  else
    echo ">> ${c} (extra discovered crate)" >&2
    extra_count=$((extra_count + 1))
  fi

  {
    echo
    echo "## ${c}"
    echo

    if [[ -f "$SRC" ]]; then
      cat "$SRC"
      included_count=$((included_count + 1))
    else
      echo "_(No NOTES.MD found at \`crates/${c}/NOTES.MD\` — skipped.)_"
      missing_any=1
      placeholder_count=$((placeholder_count + 1))
    fi

    echo
    echo "---"
    echo
  } >> "$OUT"
done

# Footer summary.
{
  echo
  echo "## Generation Summary"
  echo
  echo "- Generated at: \`$(timestamp)\`"
  echo "- Canonical crate count: \`${#CANONICAL_CRATES[@]}\`"
  echo "- Total sections emitted: \`${#CRATES[@]}\`"
  echo "- NOTES.MD files included: \`${included_count}\`"
  echo "- Missing placeholders inserted: \`${placeholder_count}\`"
  echo "- Extra discovered crates included: \`${extra_count}\`"
  echo "- STRICT_CANON: \`${STRICT_CANON}\`"
  echo
} >> "$OUT"

echo "Wrote: $OUT" >&2
echo "Included NOTES.MD files: ${included_count}" >&2
echo "Missing placeholders: ${placeholder_count}" >&2
echo "Extra discovered crates: ${extra_count}" >&2

if [[ "$missing_any" -eq 1 ]]; then
  echo "Note: one or more listed crates had no NOTES.MD; placeholders inserted." >&2
fi

if [[ "$missing_any" -eq 1 && "$FAIL_ON_MISSING" == "1" ]]; then
  echo "FAIL_ON_MISSING=1 and one or more NOTES.MD files are missing." >&2
  exit 1
fi