#!/usr/bin/env bash
set -euo pipefail

# Collect NOTES.MD from listed crates into ALLNOTES.MD at the repo root.

# Discover repo root (prefers git; falls back to script-relative)
if ROOT="$(git rev-parse --show-toplevel 2>/dev/null)"; then
  :
else
  SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
  ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
fi

OUT="$ROOT/ALLNOTES.MD"

# The crates to include (ordered)
CRATES=(
  "ron-kernel"
  "ron-bus"
  "ron-proto"
  "ron-metrics"
  "oap"
  "ron-transport"
  "ryker"
  "svc-overlay"
  "svc-dht"
  "ron-naming"
  "svc-storage"
  "svc-index"
  "ron-policy"
  "omnigate"
  "svc-gateway"
  "ron-kms"
  "svc-passport"
  "ron-auth"
  "micronode"
  "svc-registry"
)

timestamp() {
  date -u +"%Y-%m-%dT%H:%M:%SZ"
}

# Header
{
  echo "<!-- Generated by scripts/collect_notes.sh on $(timestamp) -->"
  echo "# ALLNOTES — Crate Notes Aggregation"
  echo
  echo "_This file aggregates \`NOTES.MD\` from the listed crates in order._"
  echo
  echo "## Included crates"
  for c in "${CRATES[@]}"; do
    echo "- ${c}"
  done
  echo
  echo "---"
  echo
} > "$OUT"

missing_any=0

# Append each NOTES.MD with a section header and divider
for c in "${CRATES[@]}"; do
  SRC="$ROOT/crates/$c/NOTES.MD"
  echo ">> ${c}" >&2
  {
    echo
    echo "## ${c}"
    echo
    if [[ -f "$SRC" ]]; then
      cat "$SRC"
    else
      echo "_(No NOTES.MD found at \`crates/${c}/NOTES.MD\` — skipped.)_"
      missing_any=1
    fi
    echo
    echo "---"
    echo
  } >> "$OUT"
done

echo "Wrote: $OUT" >&2
if [[ "$missing_any" -eq 1 ]]; then
  echo "Note: one or more crates had no NOTES.MD; placeholders inserted." >&2
fi
