#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_FILE="${1:-"${ROOT_DIR}/QUICKCHAIN_REVIEW_BUNDLE.MD"}"

QUICKCHAIN_FILE="${ROOT_DIR}/QUICKCHAIN.MD"
QC0A_FILE="${ROOT_DIR}/QUICKCHAIN_QC0A_COMBINED.MD"

if [ ! -f "${QUICKCHAIN_FILE}" ]; then
  echo "ERROR: missing QUICKCHAIN.MD" >&2
  exit 1
fi

if [ ! -f "${QC0A_FILE}" ]; then
  echo "ERROR: missing QUICKCHAIN_QC0A_COMBINED.MD. Run scripts/combine_quickchain_docs.sh first." >&2
  exit 1
fi

{
  echo "# QuickChain Review Bundle"
  echo
  echo "Generated by: \`scripts/combine_quickchain_review_bundle.sh\`"
  echo
  echo "Generated at UTC: \`$(date -u '+%Y-%m-%dT%H:%M:%SZ')\`"
  echo
  echo "Includes:"
  echo
  echo "- \`QUICKCHAIN.MD\`"
  echo "- \`QUICKCHAIN_QC0A_COMBINED.MD\`"
  echo
  echo "---"
  echo
  echo "<!-- BEGIN QUICKCHAIN.MD -->"
  echo
  echo "# File: \`QUICKCHAIN.MD\`"
  echo
  cat "${QUICKCHAIN_FILE}"
  echo
  echo
  echo "<!-- END QUICKCHAIN.MD -->"
  echo
  echo "---"
  echo
  echo "<!-- BEGIN QUICKCHAIN_QC0A_COMBINED.MD -->"
  echo
  echo "# File: \`QUICKCHAIN_QC0A_COMBINED.MD\`"
  echo
  cat "${QC0A_FILE}"
  echo
  echo
  echo "<!-- END QUICKCHAIN_QC0A_COMBINED.MD -->"
  echo
} > "${OUT_FILE}"

echo "QuickChain review bundle written to:"
echo "  ${OUT_FILE}"
