#!/usr/bin/env bash
set -euo pipefail

# Combines docs/quickchain/*.md and *.MD into one upload-friendly Markdown file.
#
# Default output:
#   QUICKCHAIN_QC0A_COMBINED.MD
#
# Usage:
#   scripts/combine_quickchain_docs.sh
#   scripts/combine_quickchain_docs.sh path/to/output.md
#
# Optional:
#   QUICKCHAIN_DOC_DIR=docs/quickchain scripts/combine_quickchain_docs.sh

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DOC_DIR_RAW="${QUICKCHAIN_DOC_DIR:-"docs/quickchain"}"

if [[ "${DOC_DIR_RAW}" = /* ]]; then
  DOC_DIR="${DOC_DIR_RAW}"
else
  DOC_DIR="${ROOT_DIR}/${DOC_DIR_RAW}"
fi

OUT_FILE="${1:-"${ROOT_DIR}/QUICKCHAIN_QC0A_COMBINED.MD"}"

if [ ! -d "${DOC_DIR}" ]; then
  echo "ERROR: docs directory not found: ${DOC_DIR}" >&2
  exit 1
fi

TMP_LIST="$(mktemp)"
TMP_SEEN="$(mktemp)"
trap 'rm -f "${TMP_LIST}" "${TMP_SEEN}"' EXIT

: > "${TMP_LIST}"
: > "${TMP_SEEN}"

add_if_exists() {
  local rel="$1"
  local path="${ROOT_DIR}/${rel}"

  if [ -f "${path}" ]; then
    printf '%s\n' "${path}" >> "${TMP_LIST}"
    printf '%s\n' "${path}" >> "${TMP_SEEN}"
  fi
}

# Preferred review order. This is easier for Grok/ChatGPT/human review than raw alphabetical order.
add_if_exists "docs/quickchain/README.md"
add_if_exists "docs/quickchain/PHASE_0_PRE_FLIGHT.md"
add_if_exists "docs/quickchain/THREAT_MODEL.md"
add_if_exists "docs/quickchain/DOMAIN_SEPARATION.md"
add_if_exists "docs/quickchain/ROOTS_AND_CANONICALIZATION.md"
add_if_exists "docs/quickchain/STATE_TREE_DECISION.md"
add_if_exists "docs/quickchain/CONCURRENT_HOLDS_AND_OPERATION_IDS.md"
add_if_exists "docs/quickchain/EVENT_CLASSIFICATION_AND_REWARDS.md"
add_if_exists "docs/quickchain/RETENTION_AND_DA_PRECONDITIONS.md"
add_if_exists "docs/quickchain/PHASE_2_TO_PHASE_3_CHASM.md"
add_if_exists "docs/quickchain/TEST_VECTORS.md"
add_if_exists "docs/quickchain/NO_GO_LIVE_CHECKLIST.md"

# Append any extra Markdown files not in the preferred list.
while IFS= read -r file; do
  if ! grep -Fxq "${file}" "${TMP_SEEN}"; then
    printf '%s\n' "${file}" >> "${TMP_LIST}"
  fi
done < <(find "${DOC_DIR}" -type f \( -name '*.md' -o -name '*.MD' \) | sort)

if [ ! -s "${TMP_LIST}" ]; then
  echo "ERROR: no Markdown files found in ${DOC_DIR}" >&2
  exit 1
fi

{
  echo "# QuickChain QC-0A Combined Docs"
  echo
  echo "Generated by: \`scripts/combine_quickchain_docs.sh\`"
  echo
  echo "Generated at UTC: \`$(date -u '+%Y-%m-%dT%H:%M:%SZ')\`"
  echo
  echo "Source directory:"
  echo
  echo '```text'
  printf '%s\n' "${DOC_DIR#${ROOT_DIR}/}"
  echo '```'
  echo
  echo "## Included files"
  echo

  while IFS= read -r file; do
    rel="${file#${ROOT_DIR}/}"
    echo "- \`${rel}\`"
  done < "${TMP_LIST}"

  echo
  echo "---"
  echo

  while IFS= read -r file; do
    rel="${file#${ROOT_DIR}/}"

    echo "<!-- BEGIN ${rel} -->"
    echo
    echo "# File: \`${rel}\`"
    echo

    cat "${file}"

    echo
    echo
    echo "<!-- END ${rel} -->"
    echo
    echo "---"
    echo
  done < "${TMP_LIST}"
} > "${OUT_FILE}"

echo "Combined QuickChain docs written to:"
echo "  ${OUT_FILE}"
echo
echo "Included files:"
while IFS= read -r file; do
  echo "  - ${file#${ROOT_DIR}/}"
done < "${TMP_LIST}"
