#!/usr/bin/env bash
set -euo pipefail

# RO:WHAT — Generate a repo-wide Rust-only codebundle (tree + TOC + file bodies).
# RO:WHY  — One-file share/review artifact; deterministic; excludes build outputs & junk.
# RO:OUTPUT — Default: ./CODEBUNDLE_RS.md (or 2nd arg)
# RO:INVARIANTS — stable sort; no nested target/; skip sdk/; skip junkyard/; skip experiments/

ROOT="${1:-.}"
OUT="${2:-CODEBUNDLE_RS.md}"

cd "$ROOT"

# Exclude any path containing these segments (any depth)
EXCLUDE_SEGMENTS=(
  "/.git/"
  "/target/"
  "/node_modules/"
  "/dist/"
  "/build/"
  "/sdk/"
  "/junkyard/"
  "/experiments/"
  "/.idea/"
  "/.vscode/"
)

is_excluded_path() {
  local p="$1"
  for seg in "${EXCLUDE_SEGMENTS[@]}"; do
    if [[ "$p" == *"$seg"* ]]; then
      return 0
    fi
  done
  return 1
}

anchor() {
  echo "$1" \
    | tr '[:upper:]' '[:lower:]' \
    | sed -E 's/[^a-z0-9 _-]+//g; s/[[:space:]]+/-/g; s/-+/-/g'
}

# Collect *.rs only (null-safe), filter, then stable sort
FILES_NUL="$(mktemp)"
FILES_SORTED_LF="$(mktemp)"
TREE_TMP="$(mktemp)"
trap 'rm -f "$FILES_NUL" "$FILES_SORTED_LF" "$TREE_TMP"' EXIT

while IFS= read -r -d '' f; do
  [[ "$f" != ./* ]] && f="./$f"
  if is_excluded_path "$f"; then
    continue
  fi
  printf '%s\0' "$f" >> "$FILES_NUL"
done < <(find . -type f -name '*.rs' -print0)

tr '\0' '\n' < "$FILES_NUL" | LC_ALL=C sort > "$FILES_SORTED_LF"

FILE_COUNT="$(wc -l < "$FILES_SORTED_LF" | tr -d ' ')"
if [[ "$FILE_COUNT" == "0" ]]; then
  echo "No .rs files found (after filtering)."
  exit 1
fi

# Build a filtered file tree from the exact same list
{
  echo "./"
  awk '
    function indent(n){ s=""; for(i=0;i<n;i++) s=s"  "; return s }
    {
      p=$0
      sub(/^\.\//, "", p)
      n=split(p, parts, "/")
      cur=""
      for(i=1;i<=n;i++){
        cur = (cur=="" ? parts[i] : cur"/"parts[i])
        if(!seen[cur]++){
          depth=i
          if(i<n){ print indent(depth) parts[i] "/" }
          else   { print indent(depth) parts[i] }
        }
      }
    }
  ' "$FILES_SORTED_LF"
} > "$TREE_TMP"

NOW="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
GIT_SHA="$(git rev-parse --short HEAD 2>/dev/null || echo "nogit")"
GIT_DIRTY=""
if git diff --quiet 2>/dev/null; then :; else GIT_DIRTY=" (dirty)"; fi

{
  echo "<!-- Generated by scripts/make_repo_codebundle_rs.sh on ${NOW} -->"
  echo "# Code Bundle — RustyOnions (Rust Only)"
  echo
  echo "> Generated for review/sharing. Source of truth remains the repo."
  echo "> Includes: \`*.rs\` only. Excludes: nested \`target/\`, \`sdk/\`, \`junkyard/\`, \`experiments/\`, etc."
  echo
  echo "- Root: \`$(pwd)\`"
  echo "- Git: \`${GIT_SHA}${GIT_DIRTY}\`"
  echo "- Files: \`${FILE_COUNT}\`"
  echo
  echo "## File Tree (filtered)"
  echo '```text'
  cat "$TREE_TMP"
  echo '```'
  echo
  echo "## Table of Contents"
  while IFS= read -r f; do
    rel="${f#./}"
    a="$(anchor "$rel")"
    echo "- [$rel](#${a})"
  done < "$FILES_SORTED_LF"
  echo

  while IFS= read -r f; do
    rel="${f#./}"
    a="$(anchor "$rel")"
    echo "---"
    echo
    echo "## $rel"
    echo
    echo "<a id=\"${a}\"></a>"
    echo
    echo '```rust'
    cat "$f"
    echo
    echo '```'
    echo
  done < "$FILES_SORTED_LF"
} > "$OUT"

echo "Wrote $OUT"