[package]
name = "svc-storage2"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false
description = "RustyOnions storage service - code-free scaffold (CAS over HTTP)."

[features]
amnesia = []
pq-hybrid = []
uds = []

[dependencies]
# Intentionally minimal; real pins come from workspace.
