[package]
name = "svc-storage"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[features]
# HTTP + metrics enabled by default (matches smoke script expectations)
default = ["http", "metrics"]

# Marker features; metrics wires in prometheus
http = []
metrics = ["dep:prometheus"]

# future: "tls", "uds", "pq-hybrid"

[dependencies]
# ==== HTTP stack ====
# Axum server features explicitly enabled (required for axum::serve)
axum = { version = "0.7.9", default-features = false, features = ["tokio", "http1", "http2", "json"] }
axum-extra = { version = "0.9", features = ["typed-header"] }   # TypedHeader (Range, etc.)
headers = "0.4"                                                 # Range/ETag helpers
http = "1"
hyper = "1"
tower-http = { version = "0.6.6", features = ["trace", "compression-full", "decompression-gzip", "cors", "util"] }
mime = "0.3"

# ==== Async/runtime ====
# ADD: "net" so tokio::net::TcpListener is available here
tokio = { version = "1.47.1", features = ["rt-multi-thread", "macros", "fs", "io-util", "signal", "net"] }
tokio-util = { version = "0.7", features = ["io"] }
bytes = "1.6"

# ==== Serde / utils ====
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
thiserror = "1"
once_cell = "1.19"
parking_lot = "0.12"
arc-swap = "1.7"
async-trait = "0.1"
base64 = "0.22"
time = { version = "0.3", features = ["formatting"] }

# ==== Observability ====
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
prometheus = { version = "0.14", optional = true }  # gated by `metrics` feature

# ==== Content addressing / helpers ====
blake3 = "1.5"
hex = "0.4"

# ==== RON crates (workspace paths) ====
ron-kernel = { path = "../ron-kernel" }
ron-metrics = { path = "../ron-metrics" }
ron-proto  = { path = "../ron-proto" }
ron-naming = { path = "../ron-naming" }

[dev-dependencies]
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls-native-roots", "http2", "json"] }
tokio   = { version = "1.47.1", features = ["rt-multi-thread", "macros"] }
