[package]
name = "svc-interop2"
version = "0.1.0"
edition = "2021"
publish = false
license = "MIT OR Apache-2.0"
description = "RustyOnions interop service (scaffold)"
readme = "README.md"
repository = "https://example.com/rustyonions"

[features]
libapi = []
tls = []
pq = []
blake3-simd = []
cli = []

[dependencies]
# Workspace-pinned deps recommended; add as you implement.
anyhow = "1"
thiserror = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
bytes = "1"
