name: ci
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install 1.80.0 --profile minimal --component rustfmt clippy
      - run: cargo fmt --all -- --check
      - run: cargo clippy -p ron-metrics2 -- -D warnings
      - run: cargo test -p ron-metrics2
      - run: cargo deny check
