name: nightly-chaos
on:
  schedule:
    - cron: "0 3 * * *"
jobs:
  chaos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.80.0
      - name: Run ignored chaos tests (placeholder)
        run: cargo test -p ron-bus2 -- --ignored --nocapture
