name: chaos
on:
  workflow_dispatch: {}
jobs:
  chaos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo 'inject latency/drop into mocked DHT during tests; stub only'
