name: render-mermaid
on: [push, pull_request]
jobs:
  mmdc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm i -g @mermaid-js/mermaid-cli
      - run: |
          for f in $(git ls-files 'crates/svc-mailbox2/docs/diagrams/*.mmd'); do
            out="${f%.mmd}.svg"
            echo "render: $f -> $out"
            mmdc -i "$f" -o "$out"
          done

