[package]
name = "svc-mailbox2-fuzz"
version = "0.1.0"
publish = false
edition = "2021"

[dependencies]
libfuzzer-sys = { version = "0.4", features = ["arbitrary-derive"] }

[workspace]
members = []

