[package]
name = "ron-token"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
ron-ledger = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
