name: ron-bus-ci
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.80.0
          components: rustfmt, clippy
      - run: cargo fmt --all --check
      - run: cargo clippy -p ron-bus --all-targets -- -D warnings
      - run: cargo test   -p ron-bus --all-features
      - run: cargo test   -p ron-bus --doc
