name: ron-bus CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: ron-bus

      - name: Build (all targets)
        run: |
          cargo build --workspace --all-targets

      - name: Format check
        run: |
          cargo fmt --all -- --check

      - name: Clippy (deny warnings)
        run: |
          cargo clippy --workspace --all-targets -- -D warnings

      - name: Test
        run: |
          cargo test --workspace

      # Public API surface snapshot
      # NOTE: This currently reports the API and *does not* gate the build.
      # Once you add a baseline file + diff step, switch continue-on-error to false.
      - name: Install cargo-public-api
        run: |
          cargo install cargo-public-api --locked

      - name: Public API report (ron-bus)
        continue-on-error: true
        run: |
          cargo public-api -p ron-bus
