name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  rust:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy,rustfmt

      - name: Cache cargo registry + target
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Show versions
        run: |
          rustc -V
          cargo -V

      - name: Format check
        run: cargo fmt --all --check

      - name: Clippy (deny warnings)
        run: cargo clippy --workspace --all-targets -- -D warnings

      - name: Build (workspace)
        run: cargo build --workspace --all-targets

      - name: Test (workspace)
        run: cargo test --workspace --all-targets -- --nocapture

  supplychain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install cargo-deny
        run: cargo install cargo-deny --locked

      - name: Cargo deny checks
        run: cargo deny check

  api-surface:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install public-api
        run: cargo install cargo-public-api --locked

      - name: Public API (ron-kernel)
        run: |
          cargo public-api -p ron-kernel
          # To enforce a baseline later, commit a text snapshot and diff against it in this step.
