name: ron-kernel Public API

on:
  pull_request:
    paths:
      - "crates/ron-kernel/**"
      - ".github/workflows/ron-kernel-public-api.yml"

jobs:
  public-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.80.0
      - uses: cargo-bins/cargo-binstall@main
      - run: cargo binstall -y cargo-public-api
      - name: Check public API drift
        run: cargo public-api -p ron-kernel --deny changed
