[package]
name = "svc-overlay"
version = "0.1.0"
edition = "2021"
# NOTE: Dependencies are inherited from [workspace.dependencies] at the repo root to avoid drift.
# Add only crate-local features here. Keep optional deps feature-gated.

[features]
default = []
arti = []     # Tor/Arti transport via ron-transport (optional)
quic = []     # QUIC transport (optional)
tls = []      # TLS transport (optional)
pq = []       # Post-quantum hybrid posture flags (transport-level)
libapi = []   # Minimal embedding API
cli = []      # CLI surface for the binary

[dev-dependencies]
# Add test-only tooling here as needed by the workspace.
