[package]
publish = false

name = "svc-overlay"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
ron-bus = { path = "../ron-bus" }
rmp-serde = "1.3"
serde = { version = "1.0", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
anyhow = "1.0"
workspace-hack = { version = "0.1", path = "../../workspace-hack" }
