[package]
publish = false

name = "svc-overlay"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = { workspace = true }
ron-bus = { workspace = true }
rmp-serde = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "fmt"] }
workspace-hack = { version = "0.1", path = "../../workspace-hack" }
